#!/bin/bash

# Strip out ".xcodeproj" extension to enable tab completion for this script in the ios-register repo
module_name=${1%.xcodeproj}

./Scripts/BazelLocal/generate_xcode_project_with_bazel.rb $module_name -an $module_name
