#!/bin/bash
killall Xcode
rm -rf ~/Library/Developer/Xcode/DerivedData

xcodePath=$(xcode-select -p)
developerDirectoryPathComponent="/Contents/Developer"
xcodePath=${xcodePath%"$developerDirectoryPathComponent"} # https://stackoverflow.com/a/16623897

xed . || open $xcodePath
